### ISSUE TITLE
Calculating wrong cgpa

### ISSUE THREAD

**Issue by GGSIPUResultTracker** [GGSIPUResultTracker/ggsipu_results_extractor#1]
### CGPA of students who are absent in one or more papers are calculated wrong.

In [this result pdf](http://ggsipu.ac.in/ExamResults/2019/280819/2015_032_B.TECH(CSE)_DECLARE_RESULT_MAY2019.pdf) cgpa of roll number _#02516403218_ is calculated as 9.0 but he/she was present in only three subjects.

**Comment by ashutoshvarma** [comment]
CGPA calculating function was ignoring subjects in which student was absent.
Fix this in #[83cb2cc](https://github.com/GGSIPUResultTracker/ggsipu_results_extractor/commit/83cb2ccf9dd94a4dc577c08c5cb016f6dcee2e0f)
